include: 'http://git.xiaoyanzhang.com/one-programmer/templates/raw/master/vue/.gitlab-ci.yml'
variables:
  PRO_HOST: tcp://47.104.81.121:22375
test:
  stage: test
  dependencies:
  - build
  script:
  - docker run --rm "${IMAGE_NAME}:${CI_COMMIT_SHA}" npm run test:unit
  tags:
    - dev
    - shell
  except:
    - schedules