include: 'http://git.xiaoyanzhang.com/one-programmer/templates/raw/master/vue/.gitlab-ci.yml'

test:
  stage: test
  dependencies:
  - build
  script:
  - docker run --rm "${IMAGE_NAME}:${CI_COMMIT_SHA}" npm run test:unit
  tags:
    - dev
    - shell
  except:
    - schedules

pro1_deploy:
  extends: .pro_deploy
  variables:
    PRO_HOST: 47.103.69.160

pro2_deploy:
  extends: .pro_deploy
  variables:
    PRO_HOST: 47.103.85.240