include: 'http://git.xiaoyanzhang.com/one-programmer/templates/raw/master/vue/.gitlab-ci.yml'

test:
  stage: test
  dependencies:
  - build
  script:
  - docker run --rm "${IMAGE_NAME}:${CI_COMMIT_SHA}" npm run test:unit
  tags:
    - dev
    - shell
  except:
    - schedules

pro1_deploy:
  extends: .production_deploy
  variables:
    PRO_HOST: tcp://47.103.69.160:22375

pro2_deploy:
  extends: .production_deploy
  variables:
    PRO_HOST: tcp://47.103.85.240:22375